### ISSUE TITLE
Replace "enter new contract" button on dashboard with "add contractor"

### ISSUE THREAD

**Issue by acolter** [18F/ogp-payroll#113]
Since we've decided that contracting officers--not contractors--are the ones who will enter contract information into the system, there's no longer a need to have an "enter new contract" button on the contractor dashboard. 

Contractors would, however, want to be able to add a subcontractor to the project: primes would add first-tier subs, first-tiers would add second-tiers, etc. 

Suggest changing "enter new contract" to "add contractor." Another option would be to add a contractor from the contract page.

**Comment by hbillings** [comment]
also need to pull the “add subcontractor” page from the contract setup flow and make it its own thing
