### ISSUE TITLE
Let's create some errors on the Review Hours page!

### ISSUE THREAD

**Issue by acolter** [18F/ogp-payroll#118]
How about we add two error messages to https://pages.18f.gov/ogp-payroll/review-hours-and-earnings/. 

The first could be a wage determination error. Maybe the bricklayer is supposed to make $25 per hour, but with rate + fringe he's only getting $20. Could highlight the rate (or rate and fringe) with an error message of "Prevailing wage is $25" or something to that effect. 

The second could be a selection error. Could highlight the work classification with an error message of "Not listed on the contract." Another option would be highlighting the Carpenter (apprentice) classification with "No apprentice agreement on file" or whatever they call them.

**Comment by maya** [comment]
@acolter do you want the default page to have an error on those fields?

**Comment by acolter** [comment]
@maya The default page is fine but if there are other options let me know.

**Comment by acolter** [comment]
Errors look good to me
