### ISSUE TITLE
Add supporting detail for flagged issues 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#126]
As a user, I want to add and view descriptions for why a particular report has been flagged. 

This would be helpful for primes that are tracking multiple payrolls across different contracts and can't remember why certain items have been flagged.

**Comment by acolter** [comment]
Specifically, it would help to know who flagged the report:
- Is this a system flag (e.g., the hourly rate for carpenter doesn't match what's in the contract)
- Is this a comment I've added (e.g., a reminder to double-check whether we have documentation for an apprentice program)
- Is this a flag triggered by the contracting officer (e.g., I've found a problem, I'm sending it back to you to fix)
