### ISSUE TITLE
Dashboard View: Indicate which items that are ready to be sent have been viewed 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#127]
As a user, I want the system to tell me which of the items that I've received have been viewed. 

While the system will not require users to review entries before sending them, we want to support primes that like to review items before sending them out. This could be facilitated by showing new items in bold and once they have been viewed, leaving them unbolded. An unbolded item with a green check mark would indicate that it's ready to be sent.

**Comment by LarryBafundo** [comment]
@hbillings: not sure if this is possible given that our app is largely static, but would it be possible to simulate how it looks to "work through" the backlog of items that is shown on the dashboard? 

For example, we might show how a user could select one or more "ready to send" payrolls, send them, and have the page refresh without those items being on the list of things that require their attention. This would emphasize how the dashboard only shows what you need to take action on. 

Not a priority, just a nice to have if it's something we can do easily.

**Comment by LarryBafundo** [comment]
@maya: let's only focus on the "ready items" and see if we can just unbold a couple, to indicate that those items have been viewed. alternatively, we could look into using a different icon, but at this point, we shouldn't overthink this one.

**Comment by maya** [comment]
@LarryBafundo is this what you mean? What about the other statuses?

<img width="1031" alt="screen shot 2016-05-20 at 11 32 46 am" src="https://cloud.githubusercontent.com/assets/5249443/15437975/c6315362-1e7e-11e6-85b7-287d1567737f.png">

**Comment by LarryBafundo** [comment]
how about we unbold all of the rest as a default and just leave the bolded
items as the ready to send reports that haven't been reviewed yet.

**Comment by maya** [comment]
Like this? Keep in mind, I've done some light user testing and people had favored the bold look across the board.
<img width="1048" alt="screen shot 2016-05-20 at 11 46 02 am" src="https://cloud.githubusercontent.com/assets/5249443/15438359/a810c906-1e80-11e6-8424-7cba328e8d07.png">

**Comment by maya** [comment]
Came up with another idea using a label:

<img width="1038" alt="screen shot 2016-05-20 at 11 59 46 am" src="https://cloud.githubusercontent.com/assets/5249443/15438728/6c1ef6e6-1e82-11e6-98f6-c9e9d8a523df.png">

**Comment by LarryBafundo** [comment]
excellent!

**Comment by acolter** [comment]
Prefer bold to indicate unread over a tag.
