### ISSUE TITLE
Upload: Add drop-down that identifies which contract the uploaded data is for 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#130]
Currently the upload page asks if the file to be uploaded file is for a given contract, but the user has no way of identifying which contract the upload is for. Adding a drop-down that allows users to select which contract the import belongs to may help this feel more intuitive. 

<img width="688" alt="screen shot 2016-05-19 at 2 56 17 pm" src="https://cloud.githubusercontent.com/assets/15899668/15410989/c0edb22c-1dd1-11e6-9d5a-bdb839cadf53.png">

**Comment by LarryBafundo** [comment]
@acolter similarly, why is it important for us to ask whether or not this is the final payroll for the contract here?

**Comment by acolter** [comment]
@LarryBafundo Doesn't necessarily have to be here.
