### ISSUE TITLE
Profile View: replace current hierarchy table with the previous dashboard view 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#131]
This a nice to have, but can we swap out the current hierarchy table within the profile page with the table from the previous dashboard view? The old one looked nice and worked fairly well and could live on here. 

Replace this: 

![Uploading Screen Shot 2016-05-19 at 3.03.04 PM.png…]()

**Comment by maya** [comment]
This will not be done in the current prototype.
