### ISSUE TITLE
Dashboard: Add icon to indicate alerts 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#132]
Users may benefit from a system of alerts that indicate when new information or reports are available. We don't need to build this functionality out, but showing where it might live on the page and talking about some of the ways different types of users may be notified would be useful for future demos and the final presentation. 

cc: @acolter

**Comment by acolter** [comment]
@LarryBafundo I would limit the type of things you get alerts for to the really important stuff, like "you've been granted access to contract #abc123" and "payroll #20 for Vandelay has been returned for a correction." Would avoid issuing alerts for receiving certified payroll.

**Comment by LarryBafundo** [comment]
yes, i agree.
