### ISSUE TITLE
Setup New Payroll: Create new entry by carrying over the previous week 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#14]
As a user, I want to be create a new payroll report by selecting a previous week's entry and carrying over relevant data 

Note: This may in fact be the most common use case. People may just prefer just carrying over the previous week and making subtle changes. We need to test and optimize for this in our design and UX.

**Comment by acolter** [comment]
I think this one is relatively high priority, at least to show that it can be done.

**Comment by maya** [comment]
@acolter can you confirm which fields would need to be editable?

<img width="684" alt="screen shot 2016-05-18 at 10 21 15 am" src="https://cloud.githubusercontent.com/assets/5249443/15368378/54a226d8-1ce2-11e6-91d9-5310d984e3d8.png">

**Comment by acolter** [comment]
@maya Payroll and Week ending date.
