### ISSUE TITLE
Edit Payroll: Assign Multiple Work Classifications and Rates for an Individual

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#23]
As a user, I want to assign individuals to multiple work classifications and show how they were paid for each role.

**Comment by LarryBafundo** [comment]
Right now I believe that our prototype only shows how a user could be assigned multiple roles, but does not show the flow for actually doing this.

**Comment by hbillings** [comment]
From user testing, it sounds like maybe multiple roles are something that, while technically possible, are never actually in play.  We should make sure this is something people want to do before we put effort into it.

**Comment by LarryBafundo** [comment]
@hbillings did we hear that assigning multiple work classifications to a single worker is a rare occurrence? If so, I might have missed that. @acolter what's your take on this? 

And while I agree this may not be a high-priority interaction for us to show in the prototype, I only bring it up because we show Degliobezzi as having multiple classifications:

<img width="1014" alt="screen shot 2016-04-25 at 2 25 51 pm" src="https://cloud.githubusercontent.com/assets/15899668/14799449/691e0a80-0af1-11e6-97e6-e9b3d88a6efd.png">
.

**Comment by acolter** [comment]
Sounds like it is a rare occurrence. In fact, we've heard contractors of all sizes talk about how they will pick a single work classification with the highest rate for a worker to avoid the "context switching" of having to record time for multiple classifications for a single person. We've also heard them say that they will pick the work classification listed on the contract that is the closest to what they're actually doing in the field.

**Comment by acolter** [comment]
Sounds like we do need to accommodate multiple job classifications.

On Mon, Apr 25, 2016 at 5:26 PM, Larry Bafundo notifications@github.com
wrote:

> @hbillings https://github.com/hbillings did we hear that assigning
> multiple work classifications to a single worker is a rare occurrence? If
> so, I might have missed that. @acolter https://github.com/acolter
> what's your take on this?
> 
> And while I agree this may not be a high-priority interaction for us to
> show in the prototype, I only bring it up because we show Degliobezzi as
> having multiple classifications:
> 
> [image: screen shot 2016-04-25 at 2 25 51 pm]
> https://cloud.githubusercontent.com/assets/15899668/14799449/691e0a80-0af1-11e6-97e6-e9b3d88a6efd.png
> .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/18F/ogp-payroll/issues/23#issuecomment-214528354

## 

Innovation Specialist @ 18F
General Services Administration
1800 F St. NW, Washington, DC 20405
