### ISSUE TITLE
Certify Payroll: Generate a PDF / electronic record 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#28]
As a user, I want to generate a PDF of my completed payroll that matches the layout of Form 347 so that I can print, scan, and or retain a copy for my records.

Note: Do we need to redact information to preserve PII?

**Comment by acolter** [comment]
I think the only information that needs to be redacted is the worker's address and SSN . I think you'd want to keep the worker's full name and last four digits of SSN only.
