### ISSUE TITLE
Send Payroll: Allow Primes to send bulk payroll reports to Contracting Officer 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#30]
As a prime contractor, I want to compile and send all of the payroll reports for a given contract to my contracting officer, once all sub-contractors have submitted their materials.

The prototype should show who I am sending these materials to, based on the information that is displayed during the project/contract setup flow.

**Comment by LarryBafundo** [comment]
Show how a user would send completed payroll to the appropriate person (prime or contracting officer) based on information that is pulled from the contract.

**Comment by LarryBafundo** [comment]
there are two dimensions to this story: 

1) how a sub (or prime) submits their company's payroll to the appropriate individual 
2) how a prime would package up approved certified payroll and send them, as a group, to the contracting officer. 

**currently we only show the flow from #1, in which the send button takes you to the statement of compliance view. In cases where primes are packaging up individual records, they won't need to sign the

**Comment by maya** [comment]
@LarryBafundo Sending to prime and payroll officer are two different workflows. Please split this card.

**Comment by maya** [comment]
As talked about today, we will send all subs in one batch.

**Comment by LarryBafundo** [comment]
@maya going to make this issue focused on prime submission and will create a separate item for subs.
