### ISSUE TITLE
Prime Alerts & Notifications: Alert me when a report is ready for my review  

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#31]
As a prime contractor, I want to be notified when a subcontractor has submitted their payroll and it is ready for my review. 

Note: 
This might not be something that people want. It could potentially bombard them with notifications. But maybe there's a middle-ground where its useful?

**Comment by acolter** [comment]
I could see where getting a ping for a certified payroll that has been delayed would be useful; not sure that getting your run-of-the-mill certified payroll from 30 subs warrants an alert. I'd vote for not doing this for the MVP.

**Comment by LarryBafundo** [comment]
Agree. This is a column for ideas, however, everything in the backlog and
beyond is fair game for the prototype.

Sent from my iPhone

On Apr 29, 2016, at 8:42 AM, Angela Colter notifications@github.com wrote:

I could see where getting a ping for a certified payroll that has been
delayed would be useful; not sure that getting your run-of-the-mill
certified payroll from 30 subs warrants an alert. I'd vote for not doing
this for the MVP.
