### ISSUE TITLE
Alerts & Notifications: I want to be notified when new wage determination data is available 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#33]
As a user, I want to be notified when a relevant new wage determination data is made available.

Note: this would only apply to a job/locality related to the contract.

**Comment by acolter** [comment]
I believe that the only thing relevant is the wage determination in the contract. If the wage determination changes during the course of a contract, by understanding is that it doesn't matter. The contract is what's important.

**Comment by LarryBafundo** [comment]
This is true, unless the contract is entering an option year, in which case
you would need to update the terms with the latest from WDOL.

But definitely not a priority for the prototype and probably a minor
feature for the MVP.
