### ISSUE TITLE
Import Data: After clicking "upload" the user should go to the existing review page for a smoother transition

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#52]

**Comment by maya** [comment]
Can you share the link to the page you want them to go to?

**Comment by LarryBafundo** [comment]
@maya: we should drop the user into the review flow: 

https://pages.18f.gov/ogp-payroll/review-hours-and-earnings-prime/

<img width="1210" alt="screen shot 2016-04-25 at 2 22 24 pm" src="https://cloud.githubusercontent.com/assets/15899668/14799316/babb6244-0af0-11e6-9fcc-1ced06614401.png">

**Comment by maya** [comment]
@LarryBafundo we already link to that page on the "submit" button on the page. So after a user would have uploaded it.
