### ISSUE TITLE
Cleanup: more clearly display which records are their own within the prime dashboard 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#53]
Prime contractors need to easily differentiate their own payroll from a list of submitted subcontractor reports. Currently we indicate the prime contractors report via a yellow highlight and a status that says "review." Explore ways to more clearly indicate which report belongs to the primes and show the available action as edit, rather than review. 

<img width="991" alt="screen shot 2016-04-25 at 11 15 20 am" src="https://cloud.githubusercontent.com/assets/15899668/14794040/c8e3709c-0ad6-11e6-84e3-e5292a4f3ec5.png">

**Comment by maya** [comment]
The yellow and bold looks like an error/warning state. We need to account for this.

**Comment by maya** [comment]
Closed via #60.
