### ISSUE TITLE
Cleanup: remove ability for primes to send subcontractor reports individually 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#59]
Primes shouldn't be able to send subcontractor reports individually. Currently our prototype indicates that a user could send an individual report, while others are still outstanding. We should only enable the send payroll action when all reports have been received. 

<img width="979" alt="screen shot 2016-04-25 at 11 33 51 am" src="https://cloud.githubusercontent.com/assets/15899668/14794470/298f6dea-0ad9-11e6-8702-6b922f3f4006.png">

**Comment by maya** [comment]
Closed via #60.
