### ISSUE TITLE
Change "Date filed" to "Week ending date"

### ISSUE THREAD

**Issue by acolter** [18F/ogp-payroll#64]
On https://pages.18f.gov/ogp-payroll/welcome-prime/ change all table header instances of "Date filed" to "Week ending date" to make everything consistent.

**Comment by maya** [comment]
@acolter I'm not seeing "Date filed" at all on that page, can you send a screenshot of what you're seeing?

**Comment by LarryBafundo** [comment]
@acolter i think we can close this?

**Comment by acolter** [comment]
Looks like it's been taken care of.

On Thu, Apr 28, 2016 at 2:04 PM, Larry Bafundo notifications@github.com
wrote:

> @acolter https://github.com/acolter i think we can close this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/18F/ogp-payroll/issues/64#issuecomment-215512727

## 

Innovation Specialist @ 18F
General Services Administration
1800 F St. NW, Washington, DC 20405
