### ISSUE TITLE
Change "payrolls sent" date

### ISSUE THREAD

**Issue by acolter** [18F/ogp-payroll#65]
On https://pages.18f.gov/ogp-payroll/welcome-prime/ the “Payrolls sent on 3/14/16” wording doesn’t match up with the payrolls listed in the table above. 

Change these two instances to “Payrolls sent on 4/4/16”

**Comment by maya** [comment]
Fixed in https://github.com/18F/ogp-payroll/commit/a056694123c8e922235c6f48807d91a4280c1bc6.
