### ISSUE TITLE
Cleanup: Review Hours & Earnings - Show Contractor Name

### ISSUE THREAD

**Issue by acolter** [18F/ogp-payroll#66]
On https://pages.18f.gov/ogp-payroll/review-hours-and-earnings/ there's nothing that indicates which contractor you're looking at. Suggest adding a "Contractor" field.

**Comment by maya** [comment]
@acolter So add contractor name in the text above the table?

**Comment by LarryBafundo** [comment]
@maya 

<img width="259" alt="screen shot 2016-04-28 at 11 05 05 am" src="https://cloud.githubusercontent.com/assets/15899668/14896137/20176c04-0d31-11e6-80bc-ec3f10ea15cd.png">

Let's try to rearrange the information hierarchy on this page. Try starting with displaying the contractor-name (which company this information belongs to), the contract #, project, payroll #, and week ending date.

**Comment by acolter** [comment]
Correct.

On Thu, Apr 28, 2016 at 12:02 PM, Maya Benari notifications@github.com
wrote:

> @acolter https://github.com/acolter So add contractor name in the text
> above the table?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/18F/ogp-payroll/issues/66#issuecomment-215477855

## 

Innovation Specialist @ 18F
General Services Administration
1800 F St. NW, Washington, DC 20405
