### ISSUE TITLE
Prime Dashboard View: Allow Primes to view the reporting relationships between subs  

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#67]
As a prime contractor, I want to view the full reporting structure for a given contract, by seeing which sub-contractors report to each other and the status of their payroll for that week. 

This information should be nested (with the ability to expand/collapse) because for big projects, the amount of information displayed could overwhelm the user.

**Comment by LarryBafundo** [comment]
@maya per our earlier conversation, let's try the following scenarios on our new dashboard: 

1) a contract where a prime has 5 first-tier subs reporting to it and 2 of them, broad street apartments and industrial inc., have a few second-tier subs reporting to them. within this example, it would be helpful to show how a user could easily scan the list of first-tier subs, see that broad street and industrial inc. have subs reporting to them via an indication like bolded text, and expand the view under broad street to see the subs reporting to it. in this case, we would not show the second-tier subs for industrial inc. because we want to demonstrate how the interface would allow the user to navigate very long lists by choosing to expand and collapse individual reporting tiers. we do not want to show the entire reporting relationship by default, but allow the user to access this information easily if they choose to. 

2) a contract where we have a similar situation as above, but where one contractor has both second and third-tier contractors reporting to it. this may be rare, but it would be helpful to show. 

**with both scenarios, we should show contractors in various states - some have sent in their payroll, some have not, and a few have been flagged for revision.**

cc: @acolter (other important variations to show?)

**Comment by maya** [comment]
@LarryBafundo could you write that as a list with the **actual** names and states you want to use?

For example:
- Company A [state?]
  - Sub 1 [sent]
  - Sub 2 [not sent]
- Company B
  - Sub 1
  - Sub 1

cc: @acolter

**Comment by LarryBafundo** [comment]
I think we can recycle some of the names we're already using. 

scenario 1: contract #123 
- sub contractor A [received] 
- sub contractor B [not received]
- sub contractor C [indicated as having 2 second-tier subs reporting to it, all of them have sent their reports, but the view is collapsed]
- sub contractor D [indicated as having 3 second-tier subs reporting to it, but not all of them have sent their reports, the user has expanded the view for more detail]
  --sub 1 [received]
  --sub 2 [not received]
  --sub 3 [received, but flagged]
- sub contractor E [not received]

**Comment by maya** [comment]
What is the status of sub contractor C and D?
- sub contractor A [received] 
- sub contractor B [not received] 
- sub contractor C [?] 
  - second-tier sub [received] 
  - second-tier sub [received] 
- sub contractor D [?]
  - second-tier sub [received] 
  - second-tier sub [not received] 
  - second-tier sub [received]  *:flags: flagged *
- sub contractor E [not received]
