### ISSUE TITLE
Edit Payroll: Remember worker details for future payroll records 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#71]
The system should remember worker details once entered, so that this information can be auto-populated in future reports. 

Fields to be auto-populated may include:

--ID number
--Past work classifications 
--Previous deductions

**Comment by LarryBafundo** [comment]
@acolter: we may very well not show this in the prototype, but should this feature include remembering a worker's deductions? seems like the hours and rates paid will vary by job, but deductions may be fairly consistent.

**Comment by LarryBafundo** [comment]
@catherinedevlin note that we will want to account for storing past worker data to facilitate reporting.

**Comment by acolter** [comment]
Yes, I think the system should remember the worker and the worker's
deductions.

On Thu, Apr 28, 2016 at 3:29 PM, Larry Bafundo notifications@github.com
wrote:

> @acolter https://github.com/acolter: we may very well not show this in
> the prototype, but should this feature include remembering a worker's
> deductions? seems like the hours and rates paid will vary by job, but
> deductions may be fairly consistent.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/18F/ogp-payroll/issues/71#issuecomment-215536658

## 

Innovation Specialist @ 18F
General Services Administration
1800 F St. NW, Washington, DC 20405
