### ISSUE TITLE
Cleanup - Edit Payroll: more clearly show how fringes make-up the Davis-Bacon rate

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#72]
Our interviews suggest that it's not always clear how we're displaying the prevailing wages and fringes for a selected work classification. For example, in the attached screen shot, we show that the Davis-Bacon Rate for a marble finisher is $32.40 and the fringes to be paid is $23.85. This could be interpreted as a marble finisher should be paid $56.25, when in fact, the Davis-Bacon rate is $32.40. We've just shown how that rate is divided up by wages and fringe benefits paid. 

Consider more clearly showing the Davis-Bacon rate as the total rate to be paid, with the fringes nested below it as a component of that rate. 

<img width="290" alt="screen shot 2016-04-28 at 12 30 30 pm" src="https://cloud.githubusercontent.com/assets/15899668/14898861/f262f19a-0d3d-11e6-9ee2-c55cb2734ad2.png">

**Comment by acolter** [comment]
Suggest listing this in terms of DB wage = rate + fringe.
E.g., Davis-Bacon rate: $32.40 (includes rate ($20.00) + fringe ($12.40))
or something to that effect

**Comment by hbillings** [comment]
I think this should be fixed in the current iteration (see screenshot).
<img width="360" alt="screen shot 2016-05-09 at 10 14 08 am" src="https://cloud.githubusercontent.com/assets/509309/15121306/dc4c2482-15ce-11e6-878e-5a577617b9dc.png">
