### ISSUE TITLE
Sign and Certify Payroll: Indicate how fringe benefits are paid 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#73]
On the sign and certify page, we need to add check boxes for options A and B to show how fringe benefits were paid. They may be paid through approved plans (A) or by cash (B), or in both ways. 

<img width="1042" alt="screen shot 2016-04-28 at 12 37 57 pm" src="https://cloud.githubusercontent.com/assets/15899668/14898923/550f3128-0d3e-11e6-8ca2-0e6bdf4594f0.png">

**Comment by acolter** [comment]
I'd like to suggest that it might make sense to put these earlier in the workflow. If you are paying fringes to a union you check 4a. When you enter your worker info, the system should give you **two fields** to enter wage information: a rate field and a fringe field. 

If you are paying fringes directly to the worker, you check 4b. When you enter your worker info, the system should give you **one field** to enter wage information: a rate field. 

Wouldn't it be cool if the system knew up front which one you were using? So it would know whether to give you one field or two when entering your hours and rates info.
