### ISSUE TITLE
Edit Payroll: Allow users to attach supporting documentation for "other" deductions

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#74]
Research suggests that users would like to see greater itemization of deductions, rather than aggregating everything under "other." This is because they frequently have to provide supporting documentation that explains how deductions were paid, which will be difficult for them to do if all of this detail is consolidated into a few fields. 

For demonstration purposes, consider adding the following fields in addition to what we already have: 

--federal, state and local taxes
--social security 
--medicare 

<img width="753" alt="screen shot 2016-04-28 at 12 47 34 pm" src="https://cloud.githubusercontent.com/assets/15899668/14899158/b14f705a-0d3f-11e6-88c9-28ac22967073.png">

sample: 

<img width="472" alt="screen shot 2016-04-28 at 2 22 24 pm" src="https://cloud.githubusercontent.com/assets/15899668/14901912/b81db5ba-0d4c-11e6-97ae-20cf3a6f6cd0.png">

**Comment by LarryBafundo** [comment]
@acolter: is this how you would describe this issue?

**Comment by acolter** [comment]
It's interesting. The existing federal form lists "other." I wonder if the path of least resistance would be to offer the "Other" field that displays the total then allow users to attach an itemized list that breaks it down?

**Comment by LarryBafundo** [comment]
Let's go with your suggestion Angela.

**Comment by LarryBafundo** [comment]
Lets stick with the current arrangement, but indicate that users could append supporting documentation for the total value represented by the other deduction field.

**Comment by acolter** [comment]
Should we change the title of this issue to something like, "Allow users to attach supporting documents" or something like that?

**Comment by LarryBafundo** [comment]
@acolter updated the title.

**Comment by LarryBafundo** [comment]
@acolter can you please document your preferred way of handling of this?

**Comment by LarryBafundo** [comment]
Add a link that says "attach supporting documentation" on "View deductions" page.

**Comment by acolter** [comment]
It looks like this issue is closed, but I'm not seeing where the supporting documentation link is.
