### ISSUE TITLE
Enter payroll: Message the user when an inputted rate does not meet established minimums 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#75]
The system should notify a user when they enter in a rate that is below prevailing minimums for a given classification. Currently, the prototype does this by showing the field in red, but could more clearly indicate why the error has occurred. Consider adding messaging that explains that the rate entered does not meet the prevailing wage. 

<img width="777" alt="screen shot 2016-04-28 at 1 42 49 pm" src="https://cloud.githubusercontent.com/assets/15899668/14900921/ca1d5702-0d47-11e6-95eb-e399200381da.png">

**Comment by LarryBafundo** [comment]
@acolter thoughts on text we can use to message this error state to the user?

**Comment by maya** [comment]
The first step is deciding what the error message should read. I propose:

"This is below the Davis Bacon rate of **$43.78**."

@acolter what do you think? do we need some additional text, for example, something stating that it's OK as long as there's a good reason?

**Comment by acolter** [comment]
@maya I would suggest something like, "The rate of pay is less than the prevailing wage of $43.28" or "The hourly rate + fringe is less than the prevailing wage of $43.28."
