### ISSUE TITLE
Dashboard View: the send button should only be active when a submitted report has been selected

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#82]
Currently the send button is active regardless of what has been selected. It should only be active when a submitted report has been selected. Otherwise, it should be shown as inactive. 

<img width="1005" alt="screen shot 2016-05-06 at 5 33 10 pm" src="https://cloud.githubusercontent.com/assets/15899668/15088866/1fbe4dd0-13c7-11e6-9a67-28c0f90cf7a5.png">

**Comment by maya** [comment]
Is this one a real need or enhancement that can be done later after testing? The text already says "send selected payrolls" @acolter
