### ISSUE TITLE
Dashboard View: Update the Cumberland County Project to show a subcontractor perspective

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#84]
Currently our dashboard view is based on what a prime contractor would see. For future demonstrations, we should update the 2nd contract shown (Cumberland County Project) to reflect what a sub-contractor would see, considering that they have a more narrow view of the reporting structure. 

Primes see everything, as everything eventually roles up to the prime. 

Subs only see their direct report and the firms below them. They would not see other subcontractors reporting to the prime.

**Comment by LarryBafundo** [comment]
to clarify, let's have the cumberland county project demonstrate what a 1st tier subcontractor would see (rather than a prime) by showing just acme construction, with three 2nd tier subcontractors reporting to it (great lakes, moore and suns, and roof doctor). in this case, no other contractors should be shown unless they report to acme construction. 

also, please show the status of acme construction's own report as "flagged," to indicate how a user would know when a reviewer has flagged their report and asked for clarification or correction action. 

<img width="1026" alt="screen shot 2016-05-09 at 11 08 46 am" src="https://cloud.githubusercontent.com/assets/15899668/15123015/87f0d042-15d6-11e6-901d-4ab9ed3273f1.png">

cc: @acolter

**Comment by maya** [comment]
@LarryBafundo all the workflows are here: https://pages.18f.gov/ogp-payroll/workflows/

**Comment by LarryBafundo** [comment]
thanks, but we want to just show the different workflows from the same
dashboard.
