### ISSUE TITLE
Review: View completed reports and flag potential errors 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#86]
As a user, I want to review the reports that have been submitted to me, mark (or flag) potential areas of concern, and notify the submitter that correction action or additional clarification may be required. 

---

This story relates to 2 issues: 

1) Currently not all submitted reports are viewable (for example, Moore and Sons is shown as having submitted their report, but the user can't view it) and 2) when a user reviews a submitted report, they should not be able to "edit" it's contents since it has already been "certified."  Rather, reviewers should be able to mark (or flag) aspects that require attention and the system should notify the submitter that changes may be necessary. 

<img width="1187" alt="screen shot 2016-05-08 at 11 02 28 am" src="https://cloud.githubusercontent.com/assets/15899668/15098577/4a8d7e1c-150e-11e6-92c9-7e2d1153498b.png">

**Comment by acolter** [comment]
Agree with Larry about read-only access for submitted payroll. The only person who should be able to edit a payroll is the person who certified the payroll. I can see two use cases for editing your own payroll: 
- when there is a minor error (like a misspelling) and you simply want to correct and resubmit
- when there is a major correction (maybe after the payroll has been submitted to the contracting officer) and you actually need to send out an updated payroll. Maybe designated a "#20-edited" or something like that

If you are not the submitter, you might want to add a comment to the payroll pointing out the problem (e.g., "Elephant trainer is not a work classification on this contract. Please change this to unskilled labor for John Smith")

**Comment by LarryBafundo** [comment]
@acolter per our discussion with heather, should I close this?
