### ISSUE TITLE
Setup New Payroll: Add or Request Changes to Contracts 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#87]
Users will occasionally need to update the contract details that are established by the prime. Potential changes may include new work classifications that are in the contract, but weren't included by the prime, new subcontractors, etc. 

We should add a link to the contract details page (https://pages.18f.gov/ogp-payroll/prime/view-contract) that illustrates how a user would request or add changes to the contract. These changes would likely need to be approved by the person that setup the project (although we don't need to show that for the prototype).

<img width="1087" alt="screen shot 2016-05-08 at 11 12 07 am" src="https://cloud.githubusercontent.com/assets/15899668/15098538/04ce3cf4-150e-11e6-8c3e-bec158ba84e7.png">

**Comment by LarryBafundo** [comment]
@hbillings do you want to use this story as a place-holder for the enhancement we talked about earlier, where a subcontractor could add 2nd and 3rd tier subs to the contract? 

cc: @acolter

**Comment by hbillings** [comment]
Sounds good to me!
