### ISSUE TITLE
Add New Payroll: Select and Add Worker Details 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#89]
Research indicates that users would like the system to remember worker details so that this information doesn't have to be rekeyed on a regular basis.

As a user, I would like to select from a list of available workers and have the system auto-populate their personal details for my review. Information to be auto-populated includes: 

-First and Last Name 
-ID # 
-Previous work classifications assigned 
-Deductions 

---

For the purposes of the prototype, we could simulate how this would work by adding a table to the right of the worker detail fields that lists the workers for this company. The user would then select a worker and the applicable fields would be auto-populated with their information.

**Comment by acolter** [comment]
Keep in mind that the likely users of this functionality will be the subs who enter payroll in by hand. Those who import from a payroll system probably won't need it.

**Comment by maya** [comment]
This will not be done in the current prototype.
