### ISSUE TITLE
Combine review pages into a single page

### ISSUE THREAD

**Issue by hbillings** [18F/ogp-payroll#96]
probably ordered vertically instead of the current horizontal

**Comment by LarryBafundo** [comment]
@hbillings what do you mean by this?

**Comment by hbillings** [comment]
It's kind of clumsy to have "review hours & earnings" and "review
deductions" on two separate pages, since they're so closely related. The
only reason they're separated now is the horizontal layout won't fit on one
page. I think converting to a vertical layout would fix this and make it
more intuitive to scan. This is definitely a nice-to-have, tho.

**Comment by maya** [comment]
This will not be done in the current prototype.
